# ===============================
# [ Spring Properties ]
# ===============================
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/library?user=library&password=library
  mustache:
    expose-request-attributes: true
    suffix: .html

logging:
  level:
    com:
      github:
        greatlirik:
          DEBUG
    org:
      springframework: INFO
      hibernate: ERROR


jwt.token.secret: jwttest
jwt.token.expired: 3600000
